<?php

class PxlFancyBoxAccordion_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_fancy_box_accordion';
    protected $title = 'PXL Fancy Box Accordion';
    protected $icon = 'eicon-info-box';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Layout","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost:8888\/fastone\/wp-content\/themes\/fastone\/elements\/assets\/layout-image\/pxl_fancy_box_accordion-1.jpg"}}}]},{"name":"section_boxs","label":"Box Settings","tab":"content","controls":[{"name":"boxs","label":"","type":"repeater","default":[],"controls":[{"name":"box_image","label":"Background Image","type":"media","label_block":true},{"name":"selected_icon","label":"Content Icon","type":"icons","default":{"library":"pxli","value":"pxli-auction"}},{"name":"title_text","label":"Title","type":"textarea","default":"This is the heading","placeholder":"Enter your title","rows":3,"show_label":false},{"name":"description_text","label":"Description","type":"textarea","default":"Click edit button to change this text. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.","placeholder":"Enter your description","rows":6,"show_label":false},{"name":"button_text","label":"Button Text","type":"text","label_block":true},{"name":"link","label":"Custom Link","type":"url","placeholder":"https:\/\/your-link.com","default":{"url":"#","is_external":"on"}}]},{"name":"icon_size","label":"Icon Size","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":3,"max":100}},"selectors":{"{{WRAPPER}} .pxl-fancy-box-accordion .item-icon":"font-size: {{SIZE}}{{UNIT}};","{{WRAPPER}} .pxl-fancy-box-accordion .item-icon svg":"width: {{SIZE}}{{UNIT}}; max-height: unset;"}},{"name":"title_typography","label":"Title","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-fancy-box-accordion .item-title"},{"name":"icon_color","label":"Icon Color","type":"color","selectors":{"{{WRAPPER}} .pxl-fancy-box-accordion .item-icon i":"color: {{VALUE}};","{{WRAPPER}} .pxl-fancy-box-accordion .item-icon svg":"fill: {{VALUE}};"}},{"name":"heading_color","label":"Heading Color","type":"color","selectors":{"{{WRAPPER}} .pxl-fancy-box-accordion .item-title":"color: {{VALUE}};"}},{"name":"desc_color","label":"Description Color","type":"color","selectors":{"{{WRAPPER}} .pxl-fancy-box-accordion .item-description":"color: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}