<?php

class PxlContactForm_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_contact_form';
    protected $title = 'Pxl Contact Form 7';
    protected $icon = 'eicon-form-horizontal';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Templates","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/personal-portfolio.local\/wp-content\/themes\/ameron\/elements\/assets\/layout-image\/pxl_contact_form-1.jpg"},"2":{"label":"Layout 2","image":"http:\/\/personal-portfolio.local\/wp-content\/themes\/ameron\/elements\/assets\/layout-image\/pxl_contact_form-2.jpg"}}}]},{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"ctf7_slug","label":"Select Form","type":"select","description":"Use for layout 1 and 2 respectively","options":{"contact-form-1_copy":"Contact form 2","contact-form-1":"Contact form 1"},"default":"contact-form-1_copy"}]},{"name":"section_style_button","label":"Button Style","tab":"style","controls":[{"name":"text_align","label":"Alignment","type":"choose","control_type":"responsive","options":{"left":{"title":"Left","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"right":{"title":"Right","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-contact-form7":"text-align: {{VALUE}};"}},{"name":"button_style_tabs","control_type":"tab","tabs":[{"name":"button_style_normal","label":"Normal","controls":[{"name":"button_color","label":"Text Color","type":"color","selectors":{"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]":"color: {{VALUE}};"}},{"name":"button_background","type":"background","control_type":"group","types":["classic","gradient"],"selector":"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]"}]},{"name":"button_style_hover","label":"Hover","controls":[{"name":"button_color_hover","label":"Text Color","type":"color","selectors":{"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]:hover":"color:{{VALUE}};"}},{"name":"button_background_hover","type":"background","control_type":"group","types":["classic","gradient"],"selector":"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]:hover"}]}]}]},{"name":"textarea_size","label":"Texarea Size","tab":"style","condition":{"layout":"2"},"controls":[{"name":"message_height","type":"slider","label":"Message Height","size_units":["px"],"range":{"px":{"min":120,"max":350}},"default":{"unit":"px","size":""},"selectors":{"{{WRAPPER}} .wpcf7-form textarea.wpcf7-textarea":"height: {{SIZE}}{{UNIT}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}